from regression.ksvm import Ksvm
from regression.kdt import Kdt
from regression.kgb import Kgb
from regression.klasso import Klasso
from regression.kridge import Kridge
from regression.klinreg import Klinreg
from regression.krf import Krf
from regression.kelastic import Kelastic
from regression.kab import Kab
from regression.kbag import Kbag
from regression.kneuralnet import Kneural_network
from regression.knearest_neighbors import Knearest_neighbors
